pool: apiee-test
trigger:  none
pr: none

variables:
  repository_name: $[replace(variables['BUILD.SOURCEBRANCH'], 'refs/heads/', '')]

stages:
- stage: Precheck
  displayName: Static-Code-Analysis
  condition: always()

  jobs:
  - job: Codeanalysis
    continueOnError: false
    steps:
    - script: |
       echo $(repository_name)
       ls
       cd apigee/HelloWorld
       apigeelint -s HelloWorld/apiproxy -f table.js

- stage: Deployment
  displayName: API-Deployment
  dependsOn: Precheck
  condition: succeeded()

  jobs:
  - job: APIDeployment
    continueOnError: false
    condition: always()
    steps:
    - script: |
     
       mvn install -Pdev -Dapigee.config.options=none
  - job: integrationtest
    continueOnError: false
    dependsOn: APIDeployment
    condition: succeeded()ß
    steps:
    - script: |
       echo $(repository_name)
       
        newman run  HelloWorld/resources/postman-integration-test/MTN_CICD.postman_collection.json -e HelloWorld/resources/postman-integration-test/chenosis-dev.postman_environment.json

       